name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'pnpm'
      - run: pnpm install
      - run: pnpm run build
      - run: pnpm run test
      - run: pnpm run lint

  release:
    needs: test
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'pnpm'
          registry-url: 'https://registry.npmjs.org'
      - run: pnpm install
      - run: pnpm run build
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          # Configure git for semantic-release
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          
          # Convert workspace dependencies to * for each package
          for dir in packages/*; do
            if [ -f "$dir/package.json" ]; then
              echo "Converting workspace dependencies in $dir"
              # Use jq to replace "workspace:*" with "*" in dependencies and devDependencies
              jq '(.dependencies // {}) | with_entries(select(.value | startswith("workspace:")) | .value = "*")' "$dir/package.json" > tmp.$$.json
              jq -s '.[0] * .[1]' "$dir/package.json" tmp.$$.json > tmp2.$$.json
              jq '(.devDependencies // {}) | with_entries(select(.value | startswith("workspace:")) | .value = "*")' tmp2.$$.json > tmp.$$.json
              jq -s '.[0] * .[1]' tmp2.$$.json tmp.$$.json > "$dir/package.json"
              rm tmp.$$.json tmp2.$$.json
              
              echo "Publishing $dir"
              cd $dir
              npx semantic-release
              cd ../..
            fi
          done
